#setup
LARGURA = 1280
ALTURA = 720
FPS = 60

#PLAYER
PLAYER_START_X = 0
PLAYER_START_Y = 0
PLAYER_SIZE = 0.3
PLAYER_SPEED = 6
GUN_OFFSET_X = 55
GUNOFFSET_Y  = 25

# BULLET
SHOOT_COOLDOWN = 20
BULLET_SCALE = 5.4
BULLET_SPEED = 30
BULLET_LIFETIME = 750

# ENEMY
ENEMY_SPEED = 4

# MAPA
TILE_SCALE = 3          # cada tile 16px vira 48px
TILE_SIZE = 16 * TILE_SCALE   # 48px