#setup
LARGURA = 1280
ALTURA = 720
FPS = 60

#PLAYER
PLAYER_START_X = 400
PLAYER_START_Y = 500
PLAYER_SIZE = 0.62
PLAYER_SPEED = 6
GUN_OFFSET_X = 45
GUNOFFSET_Y = 20

# BULLET
SHOOT_COOLDOWN = 20
BULLET_SCALE = 1.4
BULLET_SPEED = 50
BULLET_LIFETIME = 750

# ENEMY
ENEMY_SPEED = 4



#yuri jogadas
TILE_SCALE = 3    # cada tile de 16px vira 48px na tela
MAP_WIDTH = 40    # largura do mapa em tiles
MAP_HEIGHT = 30   # altura do mapa em tiles